export interface Appointment  {
    rdv_id: number;
    rdv_datetime: string;
    rdv_dossier_id: number;
    hopital_id: number;
    rdv_confirmed: number;
    rdv_transfert: number;
    rdv_hotel: number;
    rdv_confirm_piece: string;
    rdv_passerport: string;
    rdv_billet: string;
    rdv_last_intervenant: number;
    rdv_message: string;
    rdv_messageen: string;
    rdv_accompagnateur: string;
    rdv_accompagnateur_phone: string;
    rdv_returndate: string;
    rdv_arrivaldate: string;
    rdv_nomhotel: string;
    rdv_adressehotel: string;
    rdv_pickup: string;
    rdv_protocolid: string;
    rdv_cancelcause: string | null;
    rdv_doctor: number;
    rdv_quotation_id: number;
    rdv_type: number;
    rdv_paid: number;
    dossier_id: number;
    dossier_datecreation: string;
    dossier_client: number;
    dossier_message: string;
    dossier_messageen: string | null;
    dossier_situation: string;
    dossier_periode: string;
    dossier_uniqId: string;
    dossier_status: number;
    dossier_destination: string;
    dossier_rdv: string;
    dossier_paiement: number;
    dossier_partnerid: number;
    dossier_consultation: number;
    dossier_supprime: string | null;
    dossier_ip: string;
    dossier_userinterested: number;
    dossier_paiementfraix: number;
    dossier_extrainfos: string;
    dossier_archived: number;
    dossier_commissionpaye: string | null;
    dossier_montantcom: string | null;
    dossier_montantcomdevise: string | null;
    dossier_responsable: number;
    dossier_affectation: string | null;
    dossier_datepaiementfraix: string | null;
    dossier_noteinterne: string | null;
    dossier_paiementmethod: string | null;
    dossier_paiementreceipt: string | null;
    viber_remind: string | null;
    dossier_available: number;
    dossier_niremind: number;
    dossier_montantcomdevise2: string | null;
    dossier_montantcomdevise3: string | null;
    dossier_montantcom2: string | null;
    dossier_montantcom3: string | null;
    dossier_source_infos: string | null;
    traffic_source: string | null;
    traffic_referer: string | null;
    dossier_creator: number;
    dossier_priority: number;
    stop_sale: number;
    hopital_id_hopital: number;
    hopital_name: string;
    hotel_id: number;
    hotel_name: string;
    hotel_stars: number;
    hotel_address: string;
};